"""Initial migration

Revision ID: 34fccb83eee3
Revises: 
Create Date: 2025-05-27 14:55:36.395871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34fccb83eee3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if index exists before dropping
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'ix_todos_id' in [idx['name'] for idx in inspector.get_indexes('todos')]:
        op.drop_index(op.f('ix_todos_id'), table_name='todos')
    if 'ix_todos_title' in [idx['name'] for idx in inspector.get_indexes('todos')]:
        op.drop_index(op.f('ix_todos_title'), table_name='todos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_todos_title'), 'todos', ['title'], unique=False)
    op.create_index(op.f('ix_todos_id'), 'todos', ['id'], unique=False)
    # ### end Alembic commands ###
